name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install gpg secret key
        run: |
          # Install gpg secret key
          cat <(echo -e "${{ secrets.MAVEN_GPG_PRIVATE_KEY }}") | gpg --batch --import
          cat <(echo -e "${{ secrets.PLAYA_SETTINGS_XML }}") | cat >> /home/runner/.m2/playa-settings.xml
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG
          cat /home/runner/.m2/playa-settings.xml
      - name: Set Version
        run: |
          echo "Tag name: $GITHUB_REF_NAME"
          mvn versions:set -DnewVersion=$GITHUB_REF_NAME
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          settings-path: /home/runner/.m2/playa-settings.xml
      - name: Publish package
        run: |
          mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} \
          clean deploy -Psonatype-oss-release
          cat /home/runner/.m2/playa-settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}